<html>
	<head>
		<meta charset="utf-8" />
    	<title>Enviar Email</title>

    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    	<link rel="stylesheet" type="text/css" href="css/estilo.css">

	</head>

	<body class="bodyemail">

		<div class="container">  

			<div class="py-3 text-center">
				<img class="d-block mx-auto mb-2" src="img/email-logo.png" alt="" width="72" height="72">
				<h2>Enviar Email</h2>
				<p class="lead">Envie um email solicitando um serviço</p>
			</div>

      		<div class="row">
      			<div class="col-md-12">
  				
					<div class="card-body font-weight-bold">
						<form action="/processaEnvio" method="POST">
                           
                           <div class="form-group">
                           	<label for="nome">Nome</label>
                           	<input type="text" name="nome" class="form-control" id="nome">
                           </div>

                           <div class="form-group">
                           	<label for="telefone">Telefone</label>
                           	<input type="text" name="telefone" class="form-control" id="telefone" placeholder="(99)999999999">
                           </div>


							<div class="form-group">
								<label for="para">Para</label>
								<input name="para" type="text" class="form-control" id="para" placeholder="williansolutions@gmail.com">
							</div>

							<div class="form-group">
								<label for="assunto">Assunto</label>
								<input name="assunto" type="text" class="form-control" id="assunto" placeholder="Assundo do e-mail">
							</div>

							<div class="form-group">
								<label for="mensagem">Mensagem</label>
								<textarea name="mensagem" class="form-control" id="mensagem"></textarea>
							</div>
							<div class="container">
								
							
							<div class="row">
								<?php
                             if($this->view->erro == 1){ ?>
                             	<span class="text text-danger">Todos os campos precisam estar preenchidos</span>                            
							 <?php } ?>
							</div>
                              </div>                           
							<button type="submit" class="btn btn-primary btn-lg">Enviar Mensagem</button>														
						</form>
					</div>
				</div>
      		</div>
      	</div>

	</body>
</html>