<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Willians Solutions</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<style type="text/css">
	.menu {
		margin-bottom: 25px;
	}

	.app {
		margin-top: 25px;
	}

	.pagina {
		border:solid 1px #DFDFDF;
		padding:25px !important;
	}

	li.list-group-item.active {
		background-color: #fff;
		border-color: #009933;
		border-left:solid 10px #009933;
	}

	li a {
		color: #212529;
	}

	li a:hover {
		text-decoration: none;
	}

	h4 {
		color: #009933 !important;
	}
</style>

<body>
	<nav class="navbar navbar-light bg-light">
		<div class="container">
			<a class="navbar-brand" href="#">
				<img src="/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
			    Willians Solutions
			</a>
		</div>
	</nav>

	<?php if ($this->view->inserir) { ?>

		<div class="bg-success pt-2 text-white d-flex justify-content-center">
			<h5>Serviço inserido com sucesso!</h5>
		</div>
		
	<?php  }  ?>


	<?php if($this->view->erro) {  ?>
		<div class="bg-danger pt-2 text-white d-flex justify-content-center">
			<h5>Por favor, Preencha todos os campos!</h5>
		</div>


	<?php } ?>
	
	<div class="container app">
		<div class="row">
			<div class="col-md-3 menu">
				<ul class="list-group">
					<li class="list-group-item"><a href="/">Servicos pendentes</a></li>
					<li class="list-group-item active"><a href="/novoServico">Novo serviço</a></li>
					<li class="list-group-item"><a href="/todosServicos">Todos serviços</a></li>
					<li class="list-group-item"><a href="/dadosServico">Dados dos serviços</a></li>
				</ul>
			</div>

			<div class="col-md-9">
				<div class="container pagina">
					<div class="row">
						<div class="col">
							<h4>Novo serviço</h4>
							<hr />

							<form action="/inserir" method="POST">
								<div class="form-group">
									<label>Cliente</label>
									<input type="text" class="form-control" name="nome" placeholder="">
									<label>Endereço</label>
									<input type="text" name="endereco" class="form-control" placeholder="Av..Rio de Janeiro">
									<label>Serviço</label>
									<input type="text" name="servico" class="form-control" placeholder="Digite o serviço">
									<label>Categoria</label>
									<select name="categoria" class="form-control">
										<option>Hardware</option>
										<option>Software</option>
										<option>Rede</option>
									</select>
									<label>Valor</label>
									<input type="number" name="valor" class="form-control" placeholder="R$">
									<label>Descrição</label>

									<textarea name="descricao" class="form-control"></textarea>
								</div>
								<button class="btn btn-success">Cadastrar</button>
							</form>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>