<!DOCTYPE html>
<html>
<head>
	<title></title>
 <style type="text/css">
   body{
    background-image: url("img/not.jpg");
  }
    nav.navbar-transparente {
    padding: 15px 0px;
    background: rgba(0,0,0,10);
  }

  .navbar-light .navbar-nav .nav-link {
    color: white;
  }

  .navbar-light .navbar-nav .nav-link:hover {
    color: #9bf0e1;
  }

  .navbar-light .navbar-toggler {
    color: rgba(255,255,255,.1);
    border-color: white;
  }

  .divisor{
    width: 1px;
    background: white;
    margin: 12px 15px;
  }

  .titulo1{
    text-transform: uppercase;
    font-family: 'Oswald', sans-serif;
    font-weight: white;
    font-size: 2.6em;
    color: white;

  }
  .subtitulo1{
    font-family: 'Roboto', sans-serif;
    font-weight: 300;
    font-size: 1.6em;
    color: white;
    text-align: center;
  }
  .btn-custom{
    color: white;
    border-radius: 500px;
    -webkit-border-radius: 500px;
    -moz-border-radius: 500px;
    text-transform: uppercase;
    transition: background 0.4s, color 0.4s;
    padding: 10px 20px;
  }
  .btn-verde{
    background: green;
  }
  .btn-verde:hover{
   color: white;
 }

 .btn-branco{
  border: 2px solid white;
}
.btn-branco:hover{
 background-color: white;
 color: black;
}




</style>

</head>
<body>
  <link rel="icon" href="img/iconehead.png">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="css/estilo.css">
  <!--HTML5Shiv-->


  <nav class="navbar navbar-expand-md navbar-light fixed-top navbar-transparente">
    <div class="container">
      <a href="#" class="navbar-brand">
        <span style="color: white; font-weight: 300; font-family: 'Roboto', sans-serif;"><img src="img/networking.svg" style="width: 50px;">Willians Solutions</span>
      </a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
        <i class="fas fa-bars text-white"></i>
      </button>
      <div class="collapse navbar-collapse" id="nav-principal">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="/enviarEmail" class="nav-link" style="color: white;">Email</a>
          </li>         
          <li class="nav-item">
            <a href="/sair" class="nav-link" style="color: white;">Sair</a>
          </li>
          
        </ul>
      </div>
    </div>
    
  </nav>

  <div class="container" style="padding-top: 200px;">
    <div class="row">
      <div class="col-sm-8">
        <h3 class="titulo1" style="color: white;">Fale conosco</h3>
        <a href="/enviarEmail" class="btn btn-lg btn-custom btn-verde">
         Enviar email
       </a>
     </div>
   </div>
 </div>


 
</body>
</html>