<?php 
//fazendo a importação do PHPmailer
require "../bibliotecas/PHPMailer/Exception.php";
require "../bibliotecas/PHPMailer/OAuth.php";
require "../bibliotecas/PHPMailer/PHPMailer.php";
require "../bibliotecas/PHPMailer/POP3.php";
require "../bibliotecas/PHPMailer/SMTP.php";

//importando os namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;




 class Mensagem {
 	private $para = null;
 	private $assunto = null;
 	private $mensagem = null;
  private $nome = null;
  private $telefone = null;
 	public $status = array('codigo_status' => null, 'descricao_status' => '');

 	public function __get($atributo){
 		return $this->$atributo;
 	}

 	public function __set($atributo, $valor){
 		$this->$atributo = $valor;
 	}

 	public function mensagemValida(){
    //validar se os dados contidos no objetos são validos. se algum campo estiver vazio, retornara falso.
 	 if(empty($this->para) || empty($this->assunto) || empty($this->mensagem) || empty($this->telefone) || empty($this->nome) ){
 	 	return false;


 	 }

 	 return true;

 	}




 }

//a logica é fazer os valores contidos no post serem recebidos nos atributos da classe atraves do __SET
 $mensagem = new Mensagem();


 $mensagem->__set('mensagem', $_POST['mensagem']);
  $mensagem->__set('para', $_POST['para']);
   $mensagem->__set('assunto', $_POST['assunto']);
   $mensagem->__set('nome', $_POST['nome']);
   $mensagem->__set('telefone', $_POST['telefone']);
  
 
// se o metodo mensagemValida() for diferente de true, exibe que a mensagem não é valida e chama o metodo (die) que mada toda a execução de código abaixo dele.
  if(!$mensagem->mensagemValida()) {
  	echo "Mensagem não é válida";
  	header('location: /enviarEmail?error=1');
  } 

  $mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = false;                                       // Enable verbose debug output
    $mail->isSMTP();                                            // Set mailer to use SMTP
    $mail->Host       = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
    $mail->Username   = 'williansgomesfilho@gmail.com';                     // SMTP username
    $mail->Password   = 'meupeitoeazul';                               // SMTP password
    $mail->SMTPSecure = 'tls';                                  // Enable TLS encryption, `ssl` also accepted
    $mail->Port       = 587;                                    // TCP port to connect to

    //Recipients
    $mail->setFrom('williansgomesfilho@gmail.com', $mensagem->__get('nome'));
    $mail->addAddress($mensagem->__get('para'));     // Add a recipient
                // Name is optional
    //$mail->addReplyTo('info@example.com', 'Information');
    //$mail->addCC('cc@example.com');
   // $mail->addBCC('bcc@example.com');

    // Attachments
   // $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
   // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name

    // Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = $mensagem->__get('assunto');
    $mail->Body    = $mensagem->__get('mensagem'). ' - Este email foi enviado pelo(a) ' . $mensagem->__get('nome'). ' - Telefone para contato ' . $mensagem->__get('telefone');
    $mail->AltBody = 'È necessario usar um client que suporte Html para ter acesso total a essa mensagem';

    $mail->send();
    $mensagem->status['codigo_status'] = 1;
    $mensagem->status['descricao_status'] =  'E-mail enviado com sucesso. Em breve entraremos em contato com os dados fornecidos para realizarmos o serviço!';
   
} catch (Exception $e) {
	$mensagem->status['codigo_status'] = 2;
    $mensagem->status['descricao_status'] = 'Não foi possivel enviar este E-mail. Por favor, tente novamente mais tarde' . $mail->ErrorInfo;
}

 ?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

	<div class="container">
		<div class="py-3 text-center">
				<img class="d-block mx-auto mb-2" src="logo.png" alt="" width="72" height="72">
				<h2>Email</h2>
				<p class="lead">Willians Solutions, Melhorando a sua vida tecnológica!</p>
			</div>
			<div class="row">
				<div class="col-md-12">
			<?php if($mensagem->status['codigo_status'] == 1 ){
        header('location:/emailSucesso');
       }
      ?>
             


			

			<?php if($mensagem->status['codigo_status'] == 2){?>

				<div class="container">
					<h1 class="display-4 text-danger">
						Ops!
					</h1>
					<p><?=$mensagem->status['descricao_status']?></p>
					<a href="/enviarEmail" class="btn btn-danger btn-lg mt-5 text-white">Voltar</a>
				</div>



			<?php } ?>





				</div>
			</div>
	</div>

</body>
</html>